# Generated by Django 4.1.4 on 2023-02-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Full_Name', models.CharField(max_length=200)),
                ('Customer_Addhar_Number', models.CharField(max_length=16)),
                ('Contact_Number', models.IntegerField()),
                ('Room_Number', models.IntegerField()),
                ('Check_In_Date', models.DateTimeField(auto_now_add=True)),
                ('Check_Out_Date', models.DateTimeField()),
                ('Room_Price', models.IntegerField()),
            ],
        ),
    ]
